export const routes = {
  home: "/",
  spaces: "/espacios",
  about: "/nosotros",
  testimonial: "/testimonios",
  contact: "/contactanos",
  terms: "/terminos",
  policy: "/politicas",
  arsenal: "/arsenal",
  blog: "/blog",
  emprendimiento: "/emprendimiento",
  suscribe: "/suscribirse",
  mentoring: "/mentoria",
  platform: "https://app.labase.pe",
};
