name: Deploy labase-web (on PR merge to main)

on:
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: deploy-labase-web
      cancel-in-progress: false
    steps:
      - name: PM2 deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: 31.97.218.15
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            pm2 deploy /root/labase-web/ecosystem.config.js production
