name: Deploy labase-web
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add VPS host key (pin)
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_PORT: ${{ secrets.VPS_PORT }}
        run: |
          : "${VPS_PORT:=22}"
          mkdir -p ~/.ssh
          ssh-keyscan -p "$VPS_PORT" "$VPS_HOST" >> ~/.ssh/known_hosts

      - name: SSH into VPS & PM2 deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script_stop: true
          script: |
            export PATH=/root/.nvm/versions/node/v22.17.1/bin:$PATH

            mkdir -p /root/.ssh
            touch /root/.ssh/config
            chmod 700 /root/.ssh
            chmod 600 /root/.ssh/config || true

            # Identidad del VPS -> GitHub (para el pull en post-deploy)
            if ! grep -q "IdentityFile /root/.ssh/id_github_labase_web" /root/.ssh/config 2>/dev/null; then
              cat <<'EOF' >> /root/.ssh/config
            Host github.com
              HostName github.com
              User git
              IdentityFile /root/.ssh/id_github_labase_web
              IdentitiesOnly yes
            EOF
            fi
            chmod 600 /root/.ssh/id_github_labase_web || true

            pm2 deploy /var/www/labase-web/ecosystem.config.cjs production --force
